name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, agent 1]
    steps:
      - uses: actions/checkout@v4
      - run: echo Hello, world!

  test-case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo second job running

  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo structure
        run: ls -R

      - name: Build with Maven
        run: mvn compile
